// Generated by delombok at Fri Sep 13 14:34:01 JST 2019
package com.rakuten.internship.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import java.util.Date;

@Entity
public class Rescue {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    private String name;
    @Column(nullable = false)
    private String title;
    @Column(nullable = false)
    private String language;
    @Column(nullable = false)
    private String description;
    @Column(nullable = false)
    private float latitude = 0;
    @Column(nullable = false)
    private float longitude = 0;
    private Date timeStamp;
    // TODO file upload
    private String image;
    private boolean isSolved;

    @PrePersist
    private void onPrePersist() {
        if (timeStamp == null) {
            this.timeStamp = new Date();
        }
    }

    /**
     * <p>
     * a = sin²(Δφ/2) + cos φ1 ⋅ cos φ2 ⋅ sin²(Δλ/2)
     * c = 2 ⋅ atan2( √a, √(1−a) )
     * d = R ⋅ c
     *
     * @param latitude  緯度
     * @param longitude 経度
     * @return distance(km)
     */
    public double getDistance(final double latitude, final double longitude) {
        final double radius = 6371;
        final double latitudeDelta = Math.toRadians(this.latitude) - Math.toRadians(latitude);
        final double longitudeDelta = Math.toRadians(this.longitude) - Math.toRadians(longitude);
        final double latitudeRadian1 = Math.toRadians(latitude);
        final double latitudeRadian2 = Math.toRadians(this.latitude);
        final double sinOfHalfOfLatitudeDelta = Math.sin(latitudeDelta / 2);
        final double sinOfHalfOfLongitudeDelta = Math.sin(longitudeDelta / 2);
        final double a = Math.pow(sinOfHalfOfLatitudeDelta, 2) + Math.cos(latitudeRadian2) * Math.cos(latitudeRadian1) * Math.pow(sinOfHalfOfLongitudeDelta, 2);
        final double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        return radius * c;
    }

    @java.lang.SuppressWarnings("all")
    public Rescue() {
    }

    @java.lang.SuppressWarnings("all")
    public long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getLanguage() {
        return this.language;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public float getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public float getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public Date getTimeStamp() {
        return this.timeStamp;
    }

    @java.lang.SuppressWarnings("all")
    public String getImage() {
        return this.image;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isSolved() {
        return this.isSolved;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setLanguage(final String language) {
        this.language = language;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final float latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final float longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimeStamp(final Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    @java.lang.SuppressWarnings("all")
    public void setImage(final String image) {
        this.image = image;
    }

    @java.lang.SuppressWarnings("all")
    public void setSolved(final boolean isSolved) {
        this.isSolved = isSolved;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Rescue)) return false;
        final Rescue other = (Rescue) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getId() != other.getId()) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$language = this.getLanguage();
        final java.lang.Object other$language = other.getLanguage();
        if (this$language == null ? other$language != null : !this$language.equals(other$language)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        if (java.lang.Float.compare(this.getLatitude(), other.getLatitude()) != 0) return false;
        if (java.lang.Float.compare(this.getLongitude(), other.getLongitude()) != 0) return false;
        final java.lang.Object this$timeStamp = this.getTimeStamp();
        final java.lang.Object other$timeStamp = other.getTimeStamp();
        if (this$timeStamp == null ? other$timeStamp != null : !this$timeStamp.equals(other$timeStamp)) return false;
        final java.lang.Object this$image = this.getImage();
        final java.lang.Object other$image = other.getImage();
        if (this$image == null ? other$image != null : !this$image.equals(other$image)) return false;
        if (this.isSolved() != other.isSolved()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Rescue;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $id = this.getId();
        result = result * PRIME + (int) ($id >>> 32 ^ $id);
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $language = this.getLanguage();
        result = result * PRIME + ($language == null ? 43 : $language.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        result = result * PRIME + java.lang.Float.floatToIntBits(this.getLatitude());
        result = result * PRIME + java.lang.Float.floatToIntBits(this.getLongitude());
        final java.lang.Object $timeStamp = this.getTimeStamp();
        result = result * PRIME + ($timeStamp == null ? 43 : $timeStamp.hashCode());
        final java.lang.Object $image = this.getImage();
        result = result * PRIME + ($image == null ? 43 : $image.hashCode());
        result = result * PRIME + (this.isSolved() ? 79 : 97);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Rescue(id=" + this.getId() + ", name=" + this.getName() + ", title=" + this.getTitle() + ", language=" + this.getLanguage() + ", description=" + this.getDescription() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", timeStamp=" + this.getTimeStamp() + ", image=" + this.getImage() + ", isSolved=" + this.isSolved() + ")";
    }
}
